export const translations = {
  eng: {
    htmlLang: "en",
    title: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    headerWorld: "World",
    breadcrumbWorld: "WORLD",
    breadcrumbAmerica: "AMERICAS",
    readTime: "5 MIN READ",
    articleTitle: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    publishedLabel: "PUBLISHED",
    publishedTime: "March 15, 2010",
    authorPrefix: "By",
    authorName: "CNN Mystery Team",
    imageFigcaption: "A portrait of the Smith family taken after the death of their fourth daughter",
    evidenceCaption: "Evidence: The ${alat} found at the scene.",
    articleP1: "America - A 9-year-old girl was found dead under suspicious circumstances at the Smith family residence in ${lokasi} on Thursday night (01/17/1924). The victim, identified as ${namaKorban} Smith. The incident occurred just hours before the family's scheduled annual photo session on their front porch.",
    articleP2: "According to the police report, ${namaKorban}'s body was discovered in a horrific condition. Initial investigations suggest she suffered fatal injuries caused by an attack involving a ${alat}. At the scene, investigators made a chilling discovery: a strange 9-sided die and a handwritten list containing nine names, nine locations, and nine weapons.",
    articleP3: "The body was transported to the hospital for an autopsy the following day. However, the procedure was never carried out, as the corpse was reported missing under mysterious circumstances. At 6:30 AM, the medical team found the autopsy table completely empty. The only clue left behind was a blood trail that abruptly ended in the middle of the hospital corridor.",
    articleH2: "Cryptic Evidence at the Scene",
    articleP4: "The discovery of the list confirmed police suspicions that this was the work of a calculated serial killer. Further investigation revealed a crumpled piece of paper near the crime scene with the three-digit number ${kodeAngka} scribbled on it. Detectives soon cracked the code: the numbers corresponded directly to the killer's list, selecting the next victim, the location of the murder, and the weapon to be used.",
    articleP5: "The Smith family has declined to give detailed comments to the media. In a brief statement, they said they have placed their full trust in the authorities to carry out a thorough investigation.",
    articleH3: "An Anomaly in the Photograph",
    articleP6: "Despite the grief and lingering uncertainty, the Smith family proceeded with their annual photo session as a tribute to the deceased. A small empty space was left in the center of the group, as if ${namaKorban} were still standing among them.",
    articleP7: "Days after the photo was developed, reports surfaced that a faint silhouette resembling ${namaKorban}'s face had appeared in the empty space. There has been no official comment regarding the claim. However, a family source stated the photo was not destroyed, despite reportedly causing great mental anguish to some family members.",
    articleP8: "The case was never officially solved. To this day, it remains one of the region's most chilling cold cases, a haunting mystery that has captivated public attention for decades.",
    relatedTitle: "Read More",
    relatedLink1: "The Most Mysterious Criminal Cases of the 20th Century",
    relatedLink2: "History of Early 20th Century Criminal Psychology",
    relatedLink3: "The Impact of Family Tragedy on Communities",
    searchPlaceholder: "Search CNN...",
    signIn: "Sign in",
    liveTv: "Live TV",
    listen: "Listen",
    watch: "Watch",
    world: "World",
    usPolitics: "US Politics",
    business: "Business",
    markets: "Markets",
    health: "Health",
    entertainment: "Entertainment",
    tech: "Tech",
    style: "Style",
    travel: "Travel",
    followCnn: "FOLLOW CNN",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    cookieSettings: "Cookie Settings",
    adChoices: "Ad Choices",
    accessibility: "Accessibility & CC",
    about: "About",
    newsletters: "Newsletters",
    transcripts: "Transcripts",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
        },
        lokasiMap: {
            'a': 'the second-floor room', 'b': 'the attic', 'c': 'the back shed', 'd': 'the basement', 'e': 'the hallway near the kitchen',
        },
        alatMap: {
            'a': { name: 'knife', image: 'knife.png' },
            'b': { name: 'hammer', image: 'hammer.png' },
            'c': { name: 'scissors', image: 'scissors.png' },
            'd': { name: 'crowbar', image: 'crowbar.png' },
            'e': { name: 'iron rod', image: 'iron-rod.png' },
        }
    }
  },
  id: {
    htmlLang: "id",
    title: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    headerWorld: "Dunia",
    breadcrumbWorld: "DUNIA",
    breadcrumbAmerica: "AMERIKA",
    readTime: "5 MENIT",
    articleTitle: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    publishedLabel: "DITERBITKAN",
    publishedTime: "15 Maret 2010",
    authorPrefix: "Oleh",
    authorName: "Tim Misteri CNN Indonesia",
    imageFigcaption: "Potret keluarga Smith pasca kepergian putri keempatnya.",
    evidenceCaption: "Barang bukti: ${alat} yang ditemukan di lokasi kejadian.",
    articleP1: "Jakarta, CNN Indonesia - Seorang remaja perempuan berusia 9 tahun ditemukan tewas secara tidak wajar di kediaman keluarga Smith, tepatnya di ${lokasi}, Kamis malam (17/01/1924). Korban diketahui bernama ${namaKorban} Smith. Insiden terjadi hanya beberapa jam sebelum keluarga tersebut dijadwalkan menjalani sesi foto tahunan mereka di teras rumah.",
    articleP2: "Menurut laporan kepolisian, jasad ${namaKorban} ditemukan dalam kondisi mengenaskan. Dugaan awal menunjukkan korban mengalami luka fatal akibat serangan menggunakan ${alat}. Di lokasi kejadian, penyidik menemukan barang bukti berupa sebuah dadu bersisi 9 dan sebuah daftar tulisan tangan berisi 9 nama, 9 lokasi, dan 9 senjata.",
    articleP3: "Jasad korban sempat dibawa ke rumah sakit untuk proses otopsi pada keesokan harinya. Namun proses tersebut gagal dilaksanakan setelah jasad dilaporkan menghilang secara misterius. Meja otopsi ditemukan kosong oleh tim medis pada pukul 06.30 pagi. Satu-satunya petunjuk yang tersisa adalah jejak darah yang berhenti di tengah lorong rumah sakit.",
    articleH2: "Temuan Bukti Berupa Sandi",
    articleP4: "Penemuan daftar tersebut memastikan kecurigaan polisi bahwa ini adalah ulah pembunuh berantai. Penyelidikan lebih lanjut mengungkap secarik kertas lecek bertuliskan tiga digit angka yaitu ${kodeAngka} di dekat lokasi kejadian. Detektif memecahkan kode tersebut: angka-angka itu merujuk langsung pada daftar sang pembunuh untuk menentukan target berikutnya, lokasi eksekusi, dan senjata yang akan dipakai.",
    articleP5: "Keluarga Smith menolak memberikan keterangan mendetail kepada media. Namun dalam pernyataan singkat, mereka menyatakan telah menyerahkan sepenuhnya penyelidikan kepada otoritas yang berwenang.",
    articleH3: "Kejanggalan pada Foto Keluarga",
    articleP6: "Meski dalam suasana duka dan belum mendapat kepastian hukum, keluarga Smith tetap menjalani sesi foto keluarga untuk menghormati mendiang. Terlihat mereka menyisakan sedikit ruang kosong di tengah barisan seolah ${namaKorban} ikut berfoto bersama.",
    articleP7: "Beberapa hari setelah foto dicetak, muncul laporan bahwa siluet samar menyerupai wajah ${namaKorban} tampak di posisi ruang kosong tersebut. Tidak ada keterangan resmi terkait dugaan ini. Namun sumber keluarga menyebutkan bahwa cetakan foto tersebut tidak dimusnahkan meskipun konon menimbulkan tekanan batin yang hebat pada beberapa anggota keluarga.",
    articleP8: "Kasus ini tidak pernah terpecahkan secara resmi. Hingga hari ini, insiden tersebut tetap menjadi salah satu kasus yang belum terungkap di wilayah itu, sebuah misteri yang terus menarik perhatian publik selama beberapa dekade.",
    relatedTitle: "Baca Baca",
    relatedLink1: "Kasus Kriminal Paling Misterius di Abad ke-20",
    relatedLink2: "Sejarah Psikologi Kriminal Awal Abad 20",
    relatedLink3: "Dampak Tragedi Keluarga pada Komunitas",
    searchPlaceholder: "Cari CNN...",
    signIn: "Masuk",
    liveTv: "TV Langsung",
    listen: "Dengar",
    watch: "Tonton",
    world: "Dunia",
    usPolitics: "Politik AS",
    business: "Bisnis",
    markets: "Pasar",
    health: "Kesehatan",
    entertainment: "Hiburan",
    tech: "Teknologi",
    style: "Gaya",
    travel: "Wisata",
    followCnn: "IKUTI CNN",
    termsOfUse: "Ketentuan Penggunaan",
    privacyPolicy: "Kebijakan Privasi",
    cookieSettings: "Pengaturan Cookie",
    adChoices: "Pilihan Iklan",
    accessibility: "Aksesibilitas & CC",
    about: "Tentang",
    newsletters: "Buletin",
    transcripts: "Transkrip",
    copyright: "© 2025 Cable News Network. Sebuah Perusahaan Warner Bros. Discovery. Semua Hak Dilindungi Undang-Undang.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
        },
        lokasiMap: {
            'a': 'kamar lantai dua', 'b': 'loteng', 'c': 'gudang belakang', 'd': 'ruang bawah tanah', 'e': 'lorong dekat dapur',
        },
        alatMap: {
            'a': { name: 'pisau', image: 'knife.png' },
            'b': { name: 'palu', image: 'hammer.png' },
            'c': { name: 'gunting', image: 'scissors.png' },
            'd': { name: 'linggis', image: 'crowbar.png' },
            'e': { name: 'batang besi', image: 'iron-rod.png' },
        }
    }
  }
};