export const translations = {
  eng: {
    htmlLang: "en",
    title: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    headerWorld: "World",
    breadcrumbWorld: "WORLD",
    breadcrumbAmerica: "AMERICAS",
    readTime: "5 MIN READ",
    articleTitle: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    publishedLabel: "PUBLISHED",
    publishedTime: "March 15, 2010",
    authorPrefix: "By",
    authorName: "CNN Mystery Team",
    imageFigcaption: "A portrait of the Smith family taken after the death of their fourth daughter",
    evidenceCaption: "Evidence: The ${alat} found at the scene.",
    articleP1: "America: A 9-year-old girl was found dead under suspicious circumstances at the Smith family residence in ${lokasi} on Thursday night (01/17/1924). The victim, identified as ${namaKorban} Smith. The incident occurred just hours before the family's scheduled annual photo session on their front porch.",
    articleP2: "According to the police report, ${namaKorban}'s body was discovered in a horrific condition. Initial investigations suggest she suffered fatal injuries caused by an attack involving a ${alat}. At the scene, investigators found a chilling piece of evidence: a numbered list containing 9 names of individuals, 9 locations, and 9 weapons. Beside it lay a strange 9-sided die. Authorities suspect that the serial killer used the die to randomly select who the target would be, where the act would be committed, and what weapon would be used.",
    articleP3: "The body was transported to the hospital for an autopsy the following day. However, the procedure was never carried out, as the corpse was reported missing under mysterious circumstances. At 6:30 AM, the medical team found the autopsy table completely empty. The only clue left behind was a blood trail that abruptly ended in the middle of the hospital corridor.",
    articleH2: "Cryptic Evidence at the Scene",
    articleP4: "The discovery of the list confirmed police suspicions that this was the work of a calculated serial killer who left the fate of his victims to chance. Further investigation revealed a mysterious piece of paper left near the crime scene, bearing the three-digit number ${kodeAngka}. Detectives soon cracked the horrific code. The first digit selects a specific name on the list for his next target, the second digit dictates the location, and the third selects the weapon he intends to use.",
    articleP5: "The Smith family has declined to give detailed comments to the media. In a brief statement, they said they have placed their full trust in the authorities to carry out a thorough investigation.",
    articleH3: "An Anomaly in the Photograph",
    articleP6: "Despite the grief and lingering uncertainty, the Smith family proceeded with their annual photo session as a tribute to the deceased. A small empty space was left in the center of the group, as if ${namaKorban} were still standing among them.",
    articleP7: "Days after the photo was developed, reports surfaced that a faint silhouette resembling ${namaKorban}'s face had appeared in the empty space. There has been no official comment regarding the claim. However, a family source stated the photo was not destroyed, despite reportedly causing great mental anguish to some family members.",
    articleP8: "The case was never officially solved. To this day, it remains one of the region's most chilling cold cases, a haunting mystery that has captivated public attention for decades.",
    relatedTitle: "Read More",
    relatedLink1: "The Most Mysterious Criminal Cases of the 20th Century",
    relatedLink2: "History of Early 20th Century Criminal Psychology",
    relatedLink3: "The Impact of Family Tragedy on Communities",
    searchPlaceholder: "Search CNN...",
    signIn: "Sign in",
    liveTv: "Live TV",
    listen: "Listen",
    watch: "Watch",
    world: "World",
    usPolitics: "US Politics",
    business: "Business",
    markets: "Markets",
    health: "Health",
    entertainment: "Entertainment",
    tech: "Tech",
    style: "Style",
    travel: "Travel",
    followCnn: "FOLLOW CNN",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    cookieSettings: "Cookie Settings",
    adChoices: "Ad Choices",
    accessibility: "Accessibility & CC",
    about: "About",
    newsletters: "Newsletters",
    transcripts: "Transcripts",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': 'the second floor room', 'b': 'the attic', 'c': 'the back warehouse', 'd': 'the basement', 'e': 'the hallway near the kitchen',
            'f': 'the library', 'g': 'the side porch', 'h': 'the old garage', 'i': 'the dining room'
        },
        alatMap: {
            'a': { name: 'knife', image: 'knife.png' },
            'b': { name: 'hammer', image: 'hammer.png' },
            'c': { name: 'scissors', image: 'scissors.png' },
            'd': { name: 'crowbar', image: 'crowbar.png' },
            'e': { name: 'iron rod', image: 'iron-rod.png' },
            'f': { name: 'rope', image: 'rope.png' },
            'g': { name: 'poison', image: 'poison.png' },
            'h': { name: 'revolver', image: 'revolver.png' },
            'i': { name: 'axe', image: 'axe.png' }
        }
    }
  },
  id: {
    htmlLang: "id",
    title: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    headerWorld: "Dunia",
    breadcrumbWorld: "DUNIA",
    breadcrumbAmerica: "AMERIKA",
    readTime: "5 MENIT",
    articleTitle: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    publishedLabel: "DITERBITKAN",
    publishedTime: "15 Maret 2010",
    authorPrefix: "Oleh",
    authorName: "Tim Misteri CNN Indonesia",
    imageFigcaption: "Potret keluarga Smith pasca kepergian putri keempatnya.",
    evidenceCaption: "Barang bukti: ${alat} yang ditemukan di lokasi kejadian.",
    articleP1: "Jakarta, CNN Indonesia: Seorang remaja perempuan berusia 9 tahun ditemukan tewas secara tidak wajar di kediaman keluarga Smith, tepatnya di ${lokasi}, Kamis malam (17/01/1924). Korban diketahui bernama ${namaKorban} Smith. Insiden terjadi hanya beberapa jam sebelum keluarga tersebut dijadwalkan menjalani sesi foto tahunan mereka di teras rumah.",
    articleP2: "Menurut laporan kepolisian, jasad ${namaKorban} ditemukan dalam kondisi mengenaskan. Dugaan awal menunjukkan korban mengalami luka fatal akibat serangan menggunakan ${alat}. Di lokasi kejadian, penyidik menemukan barang bukti yang memicu kengerian: sebuah daftar tulisan tangan bernomor yang berisi 9 nama orang, 9 nama tempat, dan 9 senjata. Di dekatnya, tergeletak sebuah dadu aneh bersisi sembilan. Kepolisian menduga kuat bahwa pelaku adalah seorang pembunuh berantai, dan kemungkinan dadu tersebut dipakai untuk memilih secara acak siapa targetnya, di mana dia melakukan aksinya, dan senjata apa yang akan dia pakai.",
    articleP3: "Jasad korban sempat dibawa ke rumah sakit untuk proses otopsi pada keesokan harinya. Namun proses tersebut gagal dilaksanakan setelah jasad dilaporkan menghilang secara misterius. Meja otopsi ditemukan kosong oleh tim medis pada pukul 06.30 pagi. Satu-satunya petunjuk yang tersisa adalah jejak darah yang berhenti di tengah lorong rumah sakit.",
    articleH2: "Temuan Bukti Berupa Sandi",
    articleP4: "Penemuan daftar tersebut memastikan kecurigaan polisi bahwa mereka berhadapan dengan pembunuh berantai berdarah dingin. Penyelidikan lebih lanjut mengungkap keberadaan secarik kertas misterius di dekat lokasi kejadian yang bertuliskan tiga digit angka, yaitu ${kodeAngka}. Detektif segera memecahkan sandi mengerikan tersebut. Angka pertama menunjuk pada salah satu nama di daftar untuk target selanjutnya, angka kedua menentukan nama tempat, dan angka ketiga memilih senjata mana yang mau ia pakai.",
    articleP5: "Keluarga Smith menolak memberikan keterangan mendetail kepada media. Namun dalam pernyataan singkat, mereka menyatakan telah menyerahkan sepenuhnya penyelidikan kepada otoritas yang berwenang.",
    articleH3: "Kejanggalan pada Foto Keluarga",
    articleP6: "Meski dalam suasana duka dan belum mendapat kepastian hukum, keluarga Smith tetap menjalani sesi foto keluarga untuk menghormati mendiang. Terlihat mereka menyisakan sedikit ruang kosong di tengah barisan seolah ${namaKorban} ikut berfoto bersama.",
    articleP7: "Beberapa hari setelah foto dicetak, muncul laporan bahwa siluet samar menyerupai wajah ${namaKorban} tampak di posisi ruang kosong tersebut. Tidak ada keterangan resmi terkait dugaan ini. Namun sumber keluarga menyebutkan bahwa cetakan foto tersebut tidak dimusnahkan meskipun konon menimbulkan tekanan batin yang hebat pada beberapa anggota keluarga.",
    articleP8: "Kasus ini tidak pernah terpecahkan secara resmi. Hingga hari ini, insiden tersebut tetap menjadi salah satu kasus yang belum terungkap di wilayah itu, sebuah misteri yang terus menarik perhatian publik selama beberapa dekade.",
    relatedTitle: "Baca Baca",
    relatedLink1: "Kasus Kriminal Paling Misterius di Abad ke-20",
    relatedLink2: "Sejarah Psikologi Kriminal Awal Abad 20",
    relatedLink3: "Dampak Tragedi Keluarga pada Komunitas",
    searchPlaceholder: "Cari CNN...",
    signIn: "Masuk",
    liveTv: "TV Langsung",
    listen: "Dengar",
    watch: "Tonton",
    world: "Dunia",
    usPolitics: "Politik AS",
    business: "Bisnis",
    markets: "Pasar",
    health: "Kesehatan",
    entertainment: "Hiburan",
    tech: "Teknologi",
    style: "Gaya",
    travel: "Wisata",
    followCnn: "IKUTI CNN",
    termsOfUse: "Ketentuan Penggunaan",
    privacyPolicy: "Kebijakan Privasi",
    cookieSettings: "Pengaturan Cookie",
    adChoices: "Pilihan Iklan",
    accessibility: "Aksesibilitas & CC",
    about: "Tentang",
    newsletters: "Buletin",
    transcripts: "Transkrip",
    copyright: "© 2025 Cable News Network. Sebuah Perusahaan Warner Bros. Discovery. Semua Hak Dilindungi Undang-Undang.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': 'kamar lantai dua', 'b': 'loteng', 'c': 'gudang belakang', 'd': 'ruang bawah tanah', 'e': 'lorong dekat dapur',
            'f': 'perpustakaan', 'g': 'teras samping', 'h': 'garasi tua', 'i': 'ruang makan'
        },
        alatMap: {
            'a': { name: 'pisau', image: 'knife.png' },
            'b': { name: 'palu', image: 'hammer.png' },
            'c': { name: 'gunting', image: 'scissors.png' },
            'd': { name: 'linggis', image: 'crowbar.png' },
            'e': { name: 'batang besi', image: 'iron-rod.png' },
            'f': { name: 'tali', image: 'rope.png' },
            'g': { name: 'racun', image: 'poison.png' },
            'h': { name: 'revolver', image: 'revolver.png' },
            'i': { name: 'kapak', image: 'axe.png' }
        }
    }
  }
};