export const translations = {
  eng: {
    htmlLang: "en",
    title: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    headerWorld: "World",
    breadcrumbWorld: "WORLD",
    breadcrumbAmerica: "AMERICAS",
    readTime: "5 MIN READ",
    articleTitle: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    publishedLabel: "PUBLISHED",
    publishedTime: "March 15, 2010",
    authorPrefix: "By",
    authorName: "CNN Mystery Team",
    imageFigcaption: "A portrait of the Smith family taken after the death of their fourth daughter",
    evidenceCaption: "Evidence: The ${alat} found at the scene.",
    articleP1: "America — A 9-year-old girl was found dead under suspicious circumstances at the Smith family residence in ${lokasi} on Thursday night (01/17/1924). The victim, identified as ${namaKorban} Smith. The incident occurred just hours before the family's scheduled annual photo session on their front porch.",
    articleP2: "According to the police report, ${namaKorban}'s body was discovered in a horrific condition. Initial investigations suggest she suffered fatal injuries caused by an attack involving a ${alat}.",
    articleP3: "The body was transported to the hospital for an autopsy the following day. However, the procedure was never carried out, as the corpse was reported missing under mysterious circumstances. At 6:30 AM, the medical team found the autopsy table completely empty. The only clue left behind was a blood trail that abruptly ended in the middle of the hospital corridor.",
    articleH2: "Cryptic Evidence at the Scene",
    articleP4: "At the scene, investigators found a chilling piece of evidence: a numbered list containing 9 names of individuals, 9 locations, and 9 weapons. Beside it lay a strange 9-sided die. Authorities suspect that the serial killer used the die to randomly select who the target would be, where the act would be committed, and what weapon would be used. Further investigation revealed a mysterious piece of paper left nearby, bearing the three-digit number ${kodeAngka}. Detectives soon cracked the horrific code. The first digit selects a specific name on the list for his next target, the second digit dictates the location, and the third selects the weapon he intends to use.",
    articleP5: "The Smith family has declined to give detailed comments to the media. In a brief statement, they said they have placed their full trust in the authorities to carry out a thorough investigation.",
    articleH3: "An Anomaly in the Photograph",
    articleP6: "Despite the grief and lingering uncertainty, the Smith family proceeded with their annual photo session as a tribute to the deceased. A small empty space was left in the center of the group — as if ${namaKorban} were still standing among them.",
    articleP7: "Days after the photo was developed, reports surfaced that a faint silhouette resembling ${namaKorban}'s face had appeared in the empty space. There has been no official comment regarding the claim. However, a family source stated the photo was not destroyed, despite reportedly causing great mental anguish to some family members.",
    articleP8: "The case was never officially solved. To this day, it remains one of the region's most chilling cold cases, a haunting mystery that has captivated public attention for decades.",
    relatedTitle: "Read More",
    relatedLink1: "The Most Mysterious Criminal Cases of the 20th Century",
    relatedLink2: "History of Early 20th Century Criminal Psychology",
    relatedLink3: "The Impact of Family Tragedy on Communities",
    searchPlaceholder: "Search CNN...",
    signIn: "Sign in",
    liveTv: "Live TV",
    listen: "Listen",
    watch: "Watch",
    world: "World",
    usPolitics: "US Politics",
    business: "Business",
    markets: "Markets",
    health: "Health",
    entertainment: "Entertainment",
    tech: "Tech",
    style: "Style",
    travel: "Travel",
    followCnn: "FOLLOW CNN",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    cookieSettings: "Cookie Settings",
    adChoices: "Ad Choices",
    accessibility: "Accessibility & CC",
    about: "About",
    newsletters: "Newsletters",
    transcripts: "Transcripts",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': 'the second floor room', 'b': 'the attic', 'c': 'the back warehouse', 'd': 'the basement', 'e': 'the hallway near the kitchen',
            'f': 'the library', 'g': 'the side porch', 'h': 'the old garage', 'i': 'the dining room'
        },
        alatMap: {
            'a': { name: 'knife', image: 'knife.png' },
            'b': { name: 'hammer', image: 'hammer.png' },
            'c': { name: 'scissors', image: 'scissors.png' },
            'd': { name: 'crowbar', image: 'crowbar.png' },
            'e': { name: 'iron rod', image: 'iron-rod.png' },
            'f': { name: 'rope', image: 'rope.png' },
            'g': { name: 'poison', image: 'poison.png' },
            'h': { name: 'revolver', image: 'revolver.png' },
            'i': { name: 'axe', image: 'axe.png' }
        }
    }
  },
  id: {
    htmlLang: "id",
    title: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    headerWorld: "Dunia",
    breadcrumbWorld: "DUNIA",
    breadcrumbAmerica: "AMERIKA",
    readTime: "5 MENIT",
    articleTitle: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    publishedLabel: "DITERBITKAN",
    publishedTime: "15 Maret 2010",
    authorPrefix: "Oleh",
    authorName: "Tim Misteri CNN Indonesia",
    imageFigcaption: "Potret keluarga Smith pasca kepergian putri keempatnya.",
    evidenceCaption: "Barang bukti: ${alat} yang ditemukan di lokasi kejadian.",
    articleP1: "Jakarta, CNN Indonesia — Seorang remaja perempuan berusia 9 tahun ditemukan tewas secara tidak wajar di kediaman keluarga Smith, tepatnya di ${lokasi}, Kamis malam (17/01/1924). Korban diketahui bernama ${namaKorban} Smith. Insiden terjadi hanya beberapa jam sebelum keluarga tersebut dijadwalkan menjalani sesi foto tahunan mereka di teras rumah.",
    articleP2: "Menurut laporan kepolisian, jasad ${namaKorban} ditemukan dalam kondisi mengenaskan. Dugaan awal menunjukkan korban mengalami luka fatal akibat serangan menggunakan ${alat}.",
    articleP3: "Jasad korban sempat dibawa ke rumah sakit untuk proses otopsi pada keesokan harinya. Namun proses tersebut gagal dilaksanakan setelah jasad dilaporkan menghilang secara misterius. Meja otopsi ditemukan kosong oleh tim medis pada pukul 06.30 pagi. Satu-satunya petunjuk yang tersisa adalah jejak darah yang berhenti di tengah lorong rumah sakit.",
    articleH2: "Temuan Bukti Berupa Sandi",
    articleP4: "Di lokasi kejadian, penyidik menemukan barang bukti yang memicu kengerian: sebuah daftar tulisan tangan bernomor yang berisi 9 nama orang, 9 nama tempat, dan 9 senjata. Di dekatnya, tergeletak sebuah dadu aneh bersisi sembilan. Kepolisian menduga kuat bahwa pelaku adalah seorang pembunuh berantai, dan kemungkinan dadu tersebut dipakai untuk memilih secara acak siapa targetnya, di mana dia melakukan aksinya, dan senjata apa yang akan dia pakai. Penyelidikan lebih lanjut mengungkap keberadaan secarik kertas misterius di dekat lokasi kejadian yang bertuliskan tiga digit angka, yaitu ${kodeAngka}. Detektif segera memecahkan sandi mengerikan tersebut. Angka pertama menunjuk pada salah satu nama di daftar untuk target selanjutnya, angka kedua menentukan nama tempat, dan angka ketiga memilih senjata mana yang mau ia pakai.",
    articleP5: "Keluarga Smith menolak memberikan keterangan mendetail kepada media. Namun dalam pernyataan singkat, mereka menyatakan telah menyerahkan sepenuhnya penyelidikan kepada otoritas yang berwenang.",
    articleH3: "Kejanggalan pada Foto Keluarga",
    articleP6: "Meski dalam suasana duka dan belum mendapat kepastian hukum, keluarga Smith tetap menjalani sesi foto keluarga untuk menghormati mendiang. Terlihat mereka menyisakan sedikit ruang kosong di tengah barisan — seolah ${namaKorban} ikut berfoto bersama.",
    articleP7: "Beberapa hari setelah foto dicetak, muncul laporan bahwa siluet samar menyerupai wajah ${namaKorban} tampak di posisi ruang kosong tersebut. Tidak ada keterangan resmi terkait dugaan ini. Namun sumber keluarga menyebutkan bahwa cetakan foto tersebut tidak dimusnahkan meskipun konon menimbulkan tekanan batin yang hebat pada beberapa anggota keluarga.",
    articleP8: "Kasus ini tidak pernah terpecahkan secara resmi. Hingga hari ini, insiden tersebut tetap menjadi salah satu kasus yang belum terungkap di wilayah itu, sebuah misteri yang terus menarik perhatian publik selama beberapa dekade.",
    relatedTitle: "Baca Baca",
    relatedLink1: "Kasus Kriminal Paling Misterius di Abad ke-20",
    relatedLink2: "Sejarah Psikologi Kriminal Awal Abad 20",
    relatedLink3: "Dampak Tragedi Keluarga pada Komunitas",
    searchPlaceholder: "Cari CNN...",
    signIn: "Masuk",
    liveTv: "TV Langsung",
    listen: "Dengar",
    watch: "Tonton",
    world: "Dunia",
    usPolitics: "Politik AS",
    business: "Bisnis",
    markets: "Pasar",
    health: "Kesehatan",
    entertainment: "Hiburan",
    tech: "Teknologi",
    style: "Gaya",
    travel: "Wisata",
    followCnn: "IKUTI CNN",
    termsOfUse: "Ketentuan Penggunaan",
    privacyPolicy: "Kebijakan Privasi",
    cookieSettings: "Pengaturan Cookie",
    adChoices: "Pilihan Iklan",
    accessibility: "Aksesibilitas & CC",
    about: "Tentang",
    newsletters: "Buletin",
    transcripts: "Transkrip",
    copyright: "© 2025 Cable News Network. Sebuah Perusahaan Warner Bros. Discovery. Semua Hak Dilindungi Undang-Undang.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': 'kamar lantai dua', 'b': 'loteng', 'c': 'gudang belakang', 'd': 'ruang bawah tanah', 'e': 'lorong dekat dapur',
            'f': 'perpustakaan', 'g': 'teras samping', 'h': 'garasi tua', 'i': 'ruang makan'
        },
        alatMap: {
            'a': { name: 'pisau', image: 'knife.png' },
            'b': { name: 'palu', image: 'hammer.png' },
            'c': { name: 'gunting', image: 'scissors.png' },
            'd': { name: 'linggis', image: 'crowbar.png' },
            'e': { name: 'batang besi', image: 'iron-rod.png' },
            'f': { name: 'tali', image: 'rope.png' },
            'g': { name: 'racun', image: 'poison.png' },
            'h': { name: 'revolver', image: 'revolver.png' },
            'i': { name: 'kapak', image: 'axe.png' }
        }
    }
  },
  jp: {
    htmlLang: "ja",
    title: "スミス家の悲劇: 殺害された子供、消えた遺体",
    headerWorld: "世界",
    breadcrumbWorld: "世界",
    breadcrumbAmerica: "アメリカ",
    readTime: "5分で読めます",
    articleTitle: "スミス家の悲劇: 殺害された子供、消えた遺体",
    publishedLabel: "公開",
    publishedTime: "2010年3月15日",
    authorPrefix: "執筆者:",
    authorName: "CNNミステリーチーム",
    imageFigcaption: "4女の死後に撮影されたスミス家の肖像写真。",
    evidenceCaption: "証拠品: 現場で発見された${alat}。",
    articleP1: "アメリカ — 1924年1月17日の木曜日の夜、${lokasi}にあるスミス家の邸宅で、9歳の少女が不審な状況で死亡しているのが発見されました。被害者は${namaKorban}・スミスと特定されました。この事件は、家族が玄関のポーチで毎年恒例の写真撮影を行うわずか数時間前に起こりました。",
    articleP2: "警察の報告によると、${namaKorban}の遺体は凄惨な状態で発見されました。初期捜査では、${alat}を使った襲撃による致命傷を負ったことが示唆されています。",
    articleP3: "遺体は翌日、解剖のために病院に運ばれました。しかし、遺体が不可解な状況で行方不明になったため、解剖は行われませんでした。午前6時30分、医療チームは解剖台が完全に空になっているのを発見しました。唯一の残された手がかりは、病院の廊下の中央で突然途切れている血痕でした。",
    articleH2: "現場に残された暗号の証拠",
    articleP4: "現場で、捜査官たちはぞっとするような証拠を発見しました。9人の名前、9つの場所、9つの武器が書かれた番号付きのリストです。その横には奇妙な9面体のサイコロが置かれていました。警察は、連続殺人犯がこのサイコロを使って、次のターゲット、犯行現場、凶器をランダムに選ぶために使用したと強く疑っています。さらに捜査を進めると、事件現場の近くに3桁の数字「${kodeAngka}」が書かれた謎の紙切れが残されているのが発見されました。刑事たちはすぐにこの恐ろしい暗号を解読しました。最初の数字はリストから次のターゲットの名前を選び、2番目の数字は場所を決定し、3番目の数字は使用する武器を選択するものでした。",
    articleP5: "スミス家はメディアへの詳細なコメントを拒否しています。短い声明の中で、彼らは徹底的な調査を行うために当局に全幅の信頼を置いていると述べました。",
    articleH3: "家族写真の異変",
    articleP6: "悲しみと不安が残る中、スミス家は故人を追悼するために毎年恒例の写真撮影を行いました。グループの中央には — まるで${namaKorban}がまだそこに立っているかのように、小さな空白のスペースが残されていました。",
    articleP7: "写真が現像されてから数日後、その空白のスペースに${namaKorban}の顔に似たかすかなシルエットが現れたという報告が浮上しました。この主張に関する公式なコメントはありません。しかし、家族の一部のメンバーに多大な精神的苦痛をもたらしたと伝えられているにもかかわらず、その写真は破棄されなかったと家族の関係者は述べています。",
    articleP8: "この事件は公式に解決されることはありませんでした。今日に至るまで、この地域で最も背筋が凍るような未解決事件の一つであり、何十年にもわたって世間の注目を集め続けている、忘れられないミステリーです。",
    relatedTitle: "関連ニュース",
    relatedLink1: "20世紀の最も謎めいた刑事事件",
    relatedLink2: "20世紀初頭の犯罪心理学の歴史",
    relatedLink3: "家族の悲劇がコミュニティに与える影響",
    searchPlaceholder: "CNNを検索...",
    signIn: "サインイン",
    liveTv: "ライブTV",
    listen: "聴く",
    watch: "観る",
    world: "世界",
    usPolitics: "米国政治",
    business: "ビジネス",
    markets: "マーケット",
    health: "健康",
    entertainment: "エンタメ",
    tech: "テック",
    style: "スタイル",
    travel: "トラベル",
    followCnn: "CNNをフォローする",
    termsOfUse: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    cookieSettings: "クッキー設定",
    adChoices: "広告の選択",
    accessibility: "アクセシビリティ",
    about: "概要",
    newsletters: "ニュースレター",
    transcripts: "トランスクリプト",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': '2階の部屋', 'b': '屋根裏部屋', 'c': '裏の倉庫', 'd': '地下室', 'e': '台所近くの廊下',
            'f': '図書室', 'g': 'サイドポーチ', 'h': '古いガレージ', 'i': '食堂'
        },
        alatMap: {
            'a': { name: 'ナイフ', image: 'knife.png' },
            'b': { name: 'ハンマー', image: 'hammer.png' },
            'c': { name: 'ハサミ', image: 'scissors.png' },
            'd': { name: 'バール', image: 'crowbar.png' },
            'e': { name: '鉄の棒', image: 'iron-rod.png' },
            'f': { name: 'ロープ', image: 'rope.png' },
            'g': { name: '毒', image: 'poison.png' },
            'h': { name: 'リボルバー', image: 'revolver.png' },
            'i': { name: '斧', image: 'axe.png' }
        }
    }
  },
  ko: {
    htmlLang: "ko",
    title: "스미스 가족의 비극: 살해된 아이, 사라진 시신",
    headerWorld: "세계",
    breadcrumbWorld: "세계",
    breadcrumbAmerica: "아메리카",
    readTime: "5분 읽기",
    articleTitle: "스미스 가족의 비극: 살해된 아이, 사라진 시신",
    publishedLabel: "발행",
    publishedTime: "2010년 3월 15일",
    authorPrefix: "작성자:",
    authorName: "CNN 미스터리 팀",
    imageFigcaption: "넷째 딸의 죽음 이후 촬영된 스미스 가족의 초상화.",
    evidenceCaption: "증거: 현장에서 발견된 ${alat}.",
    articleP1: "아메리카 — 1924년 1월 17일 목요일 밤, ${lokasi}에 있는 스미스 가족의 자택에서 9살 소녀가 의심스러운 정황 속에 숨진 채 발견되었습니다. 피해자는 ${namaKorban} 스미스로 확인되었습니다. 이 사건은 가족이 현관 앞쪽에서 매년 찍는 가족 사진 촬영을 불과 몇 시간 앞두고 발생했습니다.",
    articleP2: "경찰 보고서에 따르면 ${namaKorban}의 시신은 끔찍한 상태로 발견되었습니다. 초기 조사에 따르면 피해자는 ${alat}을(를) 사용한 공격으로 인해 치명상을 입은 것으로 보입니다.",
    articleP3: "시신은 다음 날 부검을 위해 병원으로 옮겨졌습니다. 하지만 시신이 미스터리한 상황에서 실종되는 바람에 부검은 끝내 이루어지지 않았습니다. 오전 6시 30분, 의료진은 부검대가 완전히 비어 있는 것을 발견했습니다. 유일하게 남은 단서는 병원 복도 한가운데서 갑자기 끊긴 핏자국뿐이었습니다.",
    articleH2: "현장에 남겨진 암호 증거",
    articleP4: "현장에서 조사관들은 소름 끼치는 증거를 발견했습니다. 9명의 이름, 9개의 장소, 9개의 무기가 적힌 번호가 매겨진 목록이었습니다. 그 옆에는 이상한 9면체 주사위가 놓여 있었습니다. 당국은 연쇄 살인범이 이 주사위를 굴려 다음 희생자가 누구일지, 범행 장소가 어디일지, 어떤 무기를 사용할지 무작위로 선택하는 끔찍한 추첨을 했다고 강력히 의심하고 있습니다. 추가 조사 결과, 범죄 현장 근처에 세 자리 숫자 '${kodeAngka}'가 적힌 미스터리한 종이 조각이 남겨져 있는 것이 발견되었습니다. 형사들은 곧 이 끔찍한 암호를 해독했습니다. 첫 번째 숫자는 다음 목표물을 위한 목록의 특정 이름을 선택하고, 두 번째 숫자는 장소를 지시하며, 세 번째 숫자는 사용할 무기를 선택하는 것이었습니다.",
    articleP5: "스미스 가족은 언론에 대한 자세한 언급을 거부했습니다. 짧은 성명에서 그들은 철저한 조사를 위해 당국을 전적으로 신뢰한다고 밝혔습니다.",
    articleH3: "사진 속의 이상 현상",
    articleP6: "슬픔과 불확실성이 남아있음에도 불구하고 스미스 가족은 고인을 기리기 위해 매년 찍는 사진 촬영을 진행했습니다. 일행의 한가운데에는 — 마치 ${namaKorban}이(가) 아직 그들 사이에 서 있는 것처럼 — 작은 빈 공간이 남겨져 있었습니다.",
    articleP7: "사진이 인화된 지 며칠 후, 그 빈 공간에 ${namaKorban}의 얼굴과 닮은 희미한 실루엣이 나타났다는 보고가 표면화되었습니다. 이 주장에 대한 공식적인 논평은 없습니다. 그러나 한 가족 소식통은 그 사진이 일부 가족 구성원들에게 큰 정신적 고통을 안겨주었음에도 불구하고 파기되지 않았다고 말했습니다.",
    articleP8: "이 사건은 공식적으로 해결되지 않았습니다. 오늘날까지도 이 지역에서 가장 소름 끼치는 미제 사건 중 하나로 남아 있으며, 수십 년 동안 대중의 관심을 사로잡은 잊혀지지 않는 미스터리입니다.",
    relatedTitle: "관련 기사",
    relatedLink1: "20세기 가장 미스터리한 형사 사건들",
    relatedLink2: "20세기 초 범죄 심리학의 역사",
    relatedLink3: "가족의 비극이 지역사회에 미치는 영향",
    searchPlaceholder: "CNN 검색...",
    signIn: "로그인",
    liveTv: "라이브 TV",
    listen: "듣기",
    watch: "시청하기",
    world: "세계",
    usPolitics: "미국 정치",
    business: "비즈니스",
    markets: "시장",
    health: "건강",
    entertainment: "엔터테인먼트",
    tech: "기술",
    style: "스타일",
    travel: "여행",
    followCnn: "CNN 팔로우",
    termsOfUse: "이용약관",
    privacyPolicy: "개인정보처리방침",
    cookieSettings: "쿠키 설정",
    adChoices: "광고 선택",
    accessibility: "접근성",
    about: "정보",
    newsletters: "뉴스레터",
    transcripts: "스크립트",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor', 'b': 'Abigail', 'c': 'Lillian', 'd': 'Margaret', 'e': 'Beatrice',
            'f': 'Dorothy', 'g': 'Florence', 'h': 'Mildred', 'i': 'Virginia'
        },
        lokasiMap: {
            'a': '2층 방', 'b': '다락방', 'c': '뒷창고', 'd': '지하실', 'e': '부엌 근처 복도',
            'f': '서재', 'g': '옆쪽 현관', 'h': '오래된 차고', 'i': '식당'
        },
        alatMap: {
            'a': { name: '칼', image: 'knife.png' },
            'b': { name: '망치', image: 'hammer.png' },
            'c': { name: '가위', image: 'scissors.png' },
            'd': { name: '쇠지렛대', image: 'crowbar.png' },
            'e': { name: '쇠막대기', image: 'iron-rod.png' },
            'f': { name: '밧줄', image: 'rope.png' },
            'g': { name: '독약', image: 'poison.png' },
            'h': { name: '리볼버', image: 'revolver.png' },
            'i': { name: '도끼', image: 'axe.png' }
        }
    }
  }
};